[build]
  base = "client/"
  command = "CI= npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://spending-tracker-production.up.railway.app/api/:splat"
  status = 200
  force = false # COMMENT: ensure that we always redirect
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200