# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - name: 'Create env file'
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }}>> .env
        echo DB_URI=${{ secrets.DB_URI }}>> .env
        echo TEST_DB_URI=${{ secrets.TEST_DB_URI }}>> .env
        echo CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}>> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }}>> .env
        echo JWT_VALID_FOR=$${{ secrets.JWT_VALID_FOR }}>> .env
        cat .env
    - run: npm ci
    - run: npm run test
